export class FichaPaciente {
  idPaciente: number = 0;
  nome: string = '';
  dataNascimento: string = '';
  sexo: string = '';
  cep: string = '';
  endereco: string = '';
  numeroComplemento: string = '';
  cidade: string = '';
  estado: string = '';
  ocupacao: string = '';
  diagnosticoClinico: string = '';
  queixaPrincipal: string = '';
  hmpHma: string = '';
  medicacoes: string = '';
  examesComplementares: string = '';
  exameFisico: string = '';
  condutaClinica: string = '';
  diagnostico: string = '';
  uuid: string = '';
  linkFoto: string = '/assets/user_avatar.png';
  ativo: number = 0;
}
